[git_branch]
symbol = " "
style = "bold blue"
format = "[$symbol$branch]($style) "

[nodejs]
symbol = " "
format = "[$symbol]($style)"

[aws]
symbol = " "
format = "[$symbol]($style)"

[conda]
symbol = " "
format = "[$symbol$environment]($style)"

[dart]
symbol = " "
format = "[$symbol]($style)"

[docker_context]
symbol = " "
format = "[$symbol]($style)"

[elixir]
symbol = " "
format = "[$symbol]($style)"

[elm]
symbol = " "
format = "[$symbol]($style)"

[golang]
symbol = " "
format = "[$symbol]($style)"

[hg_branch]
symbol = " "
format = "[$symbol]($style)"

[java]
symbol = " "
format = "[$symbol]($style)"

[julia]
symbol = " "
format = "[$symbol]($style)"

[nim]
symbol = " "
format = "[$symbol]($style)"

[nix_shell]
symbol = " "
format = "[$symbol]($style)"

[package]
symbol = " "
format = "[$symbol]($style)"

[perl]
symbol = " "
format = "[$symbol]($style)"

[php]
symbol = " "
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[$symbol]($style)"

[ruby]
symbol = " "
format = "[$symbol]($style)"

[rust]
symbol = " "
style = "130"                # brown
format = "[$symbol]($style)"

[swift]
symbol = "ﯣ "
format = "[$symbol]($style)"

[gcloud]
disabled = true
